/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libreria_Taylor */

#ifndef _Included_libreria_Taylor
#define _Included_libreria_Taylor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libreria_Taylor
 * Method:    CharSenx
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_libreria_Taylor_CharSenx
  (JNIEnv *, jobject, jint);

/*
 * Class:     libreria_Taylor
 * Method:    CharCosx
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libreria_Taylor_CharCosx
  (JNIEnv *, jobject, jint);

/*
 * Class:     libreria_Taylor
 * Method:    CharLnx
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libreria_Taylor_CharLnx
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
