/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib_Sjf */

#ifndef _Included_lib_Sjf
#define _Included_lib_Sjf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib_Sjf
 * Method:    sjf
 * Signature: ([Ljava/lang/String;[I[I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_lib_Sjf_sjf
  (JNIEnv *, jobject, jobjectArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
