/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libio_Lineal */

#ifndef _Included_libio_Lineal
#define _Included_libio_Lineal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libio_Lineal
 * Method:    lineal
 * Signature: (DD[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_libio_Lineal_lineal
  (JNIEnv *, jobject, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
